codecov:
  branch: travis

coverage:
  range: 70..100
  round: down
  precision: 5

  ignore:
    - "examples/*"
    - "tests/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
