version: '3'

services:
  abci:
    build:
      context: .
      dockerfile: Dockerfile2
    image: tm-abci_abci
    environment:
      TENDERMINT_HOST: tendermint
      TENDERMINT_PORT: 26657
    expose:
      - "26658"
    command: bash -c "python examples/test_app.py"

  tendermint:
    depends_on:
      - abci
    image: tendermint/tendermint:0.24.0
    entrypoint: ''
    command: sh -c "tendermint init && tendermint node --proxy_app=abci:26658"
    expose:
      - "26657"

  tm-bench:
    build:
      context: .
      dockerfile: Dockerfile2
    image: tm-abci_abci
    depends_on:
      - tendermint
      - abci
    command: bash -c "sleep 5 && ./tm-bench -T 60 -r 2000 -c 5 -test.count 5 tendermint:26657"
